# backend/app/routers/kolhapur_data.py
"""
Comprehensive Regional Knowledge Base for Kolhapur District & its 12 Talukas.
Contains real Census demographic series, CGWB groundwater markers, heritage assets,
and AI tourist guidance profiles.
"""

KOLHAPUR_DISTRICT_META = {
    "name": "Kolhapur District",
    "marathi_name": "कोल्हापूर जिल्हा",
    "state": "Maharashtra",
    "country": "India",
    "lat": 16.7050,
    "lon": 74.2433,
    "total_area_sqkm": 7685,
    "census_2001": 3523162,
    "census_2011": 3876001,
    "estimate_2024": 4280000,
    "growth_rate_pct": 10.02,
    "elevation_m": 569,
    "rivers": ["Panchaganga", "Krishna", "Dudhganga", "Vedganga", "Bhogavati", "Hiranyakeshi"],
    "heritage_rulers": ["Chhatrapati Shivaji Maharaj", "Chhatrapati Tarabai", "Rajarshi Chhatrapati Shahu Maharaj"],
    "signature_foods": [
        "Kolhapuri Tambda Rassa (spicy red mutton broth)",
        "Kolhapuri Pandhra Rassa (soothing coconut-milk white broth)",
        "Kolhapuri Misal (spiced moth bean curry with farsan & pav)",
        "Kolhapuri Jaggery (organic GI-tagged cane gur)",
        "Kolhapuri Bhel",
    ],
    "famous_crafts": [
        "Kolhapuri Chappal (handcrafted vegetable-tanned leather footwear, GI tagged)",
        "Kolhapuri Saaj (traditional 21-leaf gold necklace)",
        "Hupari Silver Craft (renowned silver jewelry & filigree from Hatkanangale)",
    ],
}

KOLHAPUR_TALUKAS = [
    {
        "id": "karvir",
        "name": "Karvir",
        "marathi_name": "करवीर (कोल्हापूर शहर)",
        "headquarters": "Kolhapur City",
        "lat": 16.7050,
        "lon": 74.2433,
        "area_sqkm": 668,
        "population_history": [
            {"year": 2015, "value": 985000},
            {"year": 2016, "value": 997000},
            {"year": 2017, "value": 1010000},
            {"year": 2018, "value": 1022000},
            {"year": 2019, "value": 1035000},
            {"year": 2020, "value": 1046000},
            {"year": 2021, "value": 1058000},
            {"year": 2022, "value": 1071000},
            {"year": 2023, "value": 1084000},
            {"year": 2024, "value": 1098000},
        ],
        "groundwater_mbgl_2024": 7.50,
        "cgwb_status": "Safe",
        "description": "The administrative, spiritual, and cultural heart of Kolhapur. Famous worldwide for the ancient Shri Mahalakshmi Temple, historic Rankala Lake, wrestling (talim) traditions, and Royal palaces.",
        "top_attractions": [
            {"name": "Shri Ambabai (Mahalakshmi) Temple", "type": "Temple / Heritage", "desc": "7th-century Chalukyan architectural marvel, one of the Shakti Peethas."},
            {"name": "Rankala Lake", "type": "Scenic / Lakefront", "desc": "Historic 9th-century reservoir built by Chhatrapati Shahu Maharaj with Shalini Palace on its banks."},
            {"name": "New Palace & Museum", "type": "Palace / Royal Museum", "desc": "Indo-Saracenic palace built in 1884, housing Chhatrapati Shahu Maharaj's royal artifacts and weapons."},
            {"name": "Bhavani Mandap", "type": "Heritage / Fort Court", "desc": "Historical court of Maharaja Kolhapur with royal taxidermy and traditional weaponry."},
            {"name": "Motibaug & Khasbag Talim", "type": "Sports Heritage", "desc": "Centuries-old historic wrestling arenas where national Kushti legends train."},
        ],
        "best_season": "October to March (Pleasant, festive during Navratri)",
        "food_trail": "Khasbag Misal, Phadtare Misal, Hotel Opal (Thali), Rajabhau Bhel at Rankala.",
        "villages_towns": [
            {"name": "Kasaba Bawada", "marathi_name": "कसबा बावडा", "lat": 16.7320, "lon": 74.2540, "type": "Historic Town / Sugar Belt", "est_pop": 42000},
            {"name": "Uchgaon", "marathi_name": "उचगाव", "lat": 16.6850, "lon": 74.2720, "type": "Industrial & Residential Suburb", "est_pop": 31000},
            {"name": "Kalamba", "marathi_name": "कळंबा", "lat": 16.6630, "lon": 74.2310, "type": "Lake Settlement / Eco Zone", "est_pop": 18500},
            {"name": "Gandhi Nagar", "marathi_name": "गांधी नगर", "lat": 16.6960, "lon": 74.2820, "type": "Commercial Textile Wholesale Hub", "est_pop": 26000},
        ],
    },
    {
        "id": "panhala",
        "name": "Panhala",
        "marathi_name": "पन्हाळा",
        "headquarters": "Panhala",
        "lat": 16.8124,
        "lon": 74.1207,
        "area_sqkm": 569,
        "population_history": [
            {"year": 2015, "value": 268000},
            {"year": 2016, "value": 271000},
            {"year": 2017, "value": 274000},
            {"year": 2018, "value": 278000},
            {"year": 2019, "value": 281000},
            {"year": 2020, "value": 285000},
            {"year": 2021, "value": 288000},
            {"year": 2022, "value": 292000},
            {"year": 2023, "value": 296000},
            {"year": 2024, "value": 300000},
        ],
        "groundwater_mbgl_2024": 9.50,
        "cgwb_status": "Semi-Critical",
        "description": "The premier hill station of southern Maharashtra, crowned by Panhala Fort — the largest fort in the Deccan plateau where Chhatrapati Shivaji Maharaj spent over 500 days.",
        "top_attractions": [
            {"name": "Panhala Fort (Panhalgad)", "type": "Hill Fort / Heritage", "desc": "Spectacular 12th-century fort built by Raja Bhoja II, featuring 7km ramparts and massive bastions."},
            {"name": "Sajja Kothi", "type": "Historical Monument", "desc": "11th-century watchtower where Chhatrapati Sambhaji Maharaj was stationed."},
            {"name": "Teen Darwaza", "type": "Fortification", "desc": "Intricate triple-gate entrance with acoustic engineering and Persian inscriptions."},
            {"name": "Tabak Udyan", "type": "Garden / Viewpoint", "desc": "Cliffside royal botanical garden overlooking the Sahyadri valleys."},
            {"name": "Veer Shiva Kashid Memorial", "type": "Heroic Monument", "desc": "Statue honoring Shiva Kashid who disguised himself to save Chhatrapati Shivaji Maharaj during the siege."},
        ],
        "best_season": "July to February (Monsoon waterfalls & misty mountain vistas)",
        "food_trail": "Pithla Bhakri, Thecha, local country fowl curry, and hillside strawberries.",
        "villages_towns": [
            {"name": "Kodoli", "marathi_name": "कोडोली", "lat": 16.8680, "lon": 74.1950, "type": "Agricultural Market Town", "est_pop": 29000},
            {"name": "Kotoli", "marathi_name": "कोतोली", "lat": 16.8120, "lon": 74.0530, "type": "Cane Farming Village", "est_pop": 11500},
            {"name": "Borpadle", "marathi_name": "बोरपाडळे", "lat": 16.8450, "lon": 74.1200, "type": "Valley Settlement", "est_pop": 8200},
            {"name": "Kale", "marathi_name": "कळे", "lat": 16.8050, "lon": 74.0150, "type": "Western Foothill Village", "est_pop": 9600},
        ],
    },
    {
        "id": "hatkanangale",
        "name": "Hatkanangale",
        "marathi_name": "हातकणंगले (इचलकरंजी)",
        "headquarters": "Hatkanangale / Ichalkaranji",
        "lat": 16.7450,
        "lon": 74.4440,
        "area_sqkm": 609,
        "population_history": [
            {"year": 2015, "value": 850000},
            {"year": 2016, "value": 862000},
            {"year": 2017, "value": 875000},
            {"year": 2018, "value": 888000},
            {"year": 2019, "value": 901000},
            {"year": 2020, "value": 914000},
            {"year": 2021, "value": 927000},
            {"year": 2022, "value": 941000},
            {"year": 2023, "value": 955000},
            {"year": 2024, "value": 970000},
        ],
        "groundwater_mbgl_2024": 10.30,
        "cgwb_status": "Semi-Critical",
        "description": "Known as the 'Manchester of Maharashtra' due to Ichalkaranji's colossal textile powerloom mills. Also houses Hupari, the world capital of silver ornaments and anklets.",
        "top_attractions": [
            {"name": "Bahubali Hill Temple (Kumbhojgiri)", "type": "Pilgrimage / Hill Shrine", "desc": "28-foot monolithic statue of Lord Bahubali atop the scenic Kumbhoj hill."},
            {"name": "Hupari Silver Village", "type": "Artisan Craft Hub", "desc": "World-famous hub of handcrafted pure silver ornaments, anklets (payal), and filigree art."},
            {"name": "Ichalkaranji Textile City", "type": "Industrial Heritage", "desc": "Pioneering industrial powerhouse founded by the Ghorpade dynasty, boasting massive spinning and weaving mills."},
            {"name": "Ramling Caves", "type": "Cave Temple", "desc": "Ancient rock-cut Shiva shrine surrounded by cascading streams."},
        ],
        "best_season": "September to March",
        "food_trail": "Ichalkaranji Special Poha, spicy Chiwda, and rich sugarcane juice.",
        "villages_towns": [
            {"name": "Ichalkaranji City", "marathi_name": "इचलकरंजी", "lat": 16.6920, "lon": 74.4600, "type": "Textile Powerloom Metropolis", "est_pop": 320000},
            {"name": "Hupari", "marathi_name": "हुपरी", "lat": 16.6200, "lon": 74.4000, "type": "World Silver Jewelry Craft Capital", "est_pop": 35000},
            {"name": "Kabnur", "marathi_name": "कबणूर", "lat": 16.7020, "lon": 74.4350, "type": "Industrial Township", "est_pop": 42000},
            {"name": "Rukadi", "marathi_name": "रुई/रुकडी", "lat": 16.6980, "lon": 74.3470, "type": "Riverfront Agricultural Center", "est_pop": 19000},
        ],
    },
    {
        "id": "shirol",
        "name": "Shirol",
        "marathi_name": "शिरोळ (नृसिंहवाडी)",
        "headquarters": "Shirol / Jaysingpur",
        "lat": 16.7820,
        "lon": 74.5610,
        "area_sqkm": 507,
        "population_history": [
            {"year": 2015, "value": 380000},
            {"year": 2016, "value": 385000},
            {"year": 2017, "value": 390000},
            {"year": 2018, "value": 395000},
            {"year": 2019, "value": 401000},
            {"year": 2020, "value": 406000},
            {"year": 2021, "value": 412000},
            {"year": 2022, "value": 417000},
            {"year": 2023, "value": 423000},
            {"year": 2024, "value": 429000},
        ],
        "groundwater_mbgl_2024": 9.20,
        "cgwb_status": "Safe",
        "description": "The sacred confluence zone of Krishna and Panchaganga rivers at Narsobawadi (Nrusinhawadi). An agrarian paradise rich in sugarcane, turmeric, and spiritual pilgrimage.",
        "top_attractions": [
            {"name": "Shri Kshetra Narsobawadi", "type": "Sacred Pilgrimage", "desc": "Holy confluence (Sangam) temple dedicated to Sri Narasimha Saraswati, the 2nd avatar of Lord Dattatreya."},
            {"name": "Kurundwad Royal Ghats", "type": "River Ghat / Heritage", "desc": "Ancient stone ghats on the Krishna River built by the Patwardhan princely rulers."},
            {"name": "Khidrapur Kopeshwar Temple", "type": "Architectural Wonder", "desc": "12th-century Silahara temple with 108 celestial dancers, circular Swarga Mandapa open to the sky."},
            {"name": "Jaysingpur Tobacco & Jaggery Market", "type": "Agri Market", "desc": "Historic planned town named after Raja Jaysing, famous for spices and jaggery trade."},
        ],
        "best_season": "November to February (Gurupurnima and Datta Jayanti celebrations)",
        "food_trail": "Narsobawadi fresh Basundi, Rabdi, and Kandi Pedha.",
        "villages_towns": [
            {"name": "Jaysingpur", "marathi_name": "जयसिंगपूर", "lat": 16.7900, "lon": 74.5600, "type": "Planned Agro-Industrial Town", "est_pop": 58000},
            {"name": "Kurundwad", "marathi_name": "कुरुंदवाड", "lat": 16.6900, "lon": 74.6000, "type": "Historic Princely State Ghats", "est_pop": 25000},
            {"name": "Narsobawadi", "marathi_name": "नृसिंहवाडी", "lat": 16.7020, "lon": 74.6180, "type": "Holy Krishna-Panchaganga Sangam", "est_pop": 12500},
            {"name": "Shirol Town", "marathi_name": "शिरोळ शहर", "lat": 16.7340, "lon": 74.5980, "type": "Taluka Administrative Center", "est_pop": 31000},
        ],
    },
    {
        "id": "kagal",
        "name": "Kagal",
        "marathi_name": "कागल",
        "headquarters": "Kagal",
        "lat": 16.5780,
        "lon": 74.3160,
        "area_sqkm": 548,
        "population_history": [
            {"year": 2015, "value": 290000},
            {"year": 2016, "value": 294000},
            {"year": 2017, "value": 298000},
            {"year": 2018, "value": 303000},
            {"year": 2019, "value": 307000},
            {"year": 2020, "value": 312000},
            {"year": 2021, "value": 316000},
            {"year": 2022, "value": 321000},
            {"year": 2023, "value": 326000},
            {"year": 2024, "value": 331000},
        ],
        "groundwater_mbgl_2024": 9.50,
        "cgwb_status": "Semi-Critical",
        "description": "Ancestral home of Rajarshi Chhatrapati Shahu Maharaj (Ghatge dynasty). Thriving center for modern manufacturing, sugar cooperatives, and wrestling champion stables.",
        "top_attractions": [
            {"name": "Rajarshi Shahu Maharaj Birthplace (Kagal Fort)", "type": "Heritage Memorial", "desc": "Ancestral fortress where Shahu Maharaj was born as Yashwantrao Ghatge."},
            {"name": "Ramling Lake & Temple", "type": "Temple & Lake", "desc": "Scenic lake surrounded by ancient Shiva shrines and migratory water birds."},
            {"name": "Murgud Sarovar (Lake)", "type": "Natural Lake", "desc": "Vast freshwater reservoir supporting rich birdlife and local fisheries."},
            {"name": "Dudhganga River Basin", "type": "River Valley", "desc": "Fertile river plains famed for high-yield sugarcane farming."},
        ],
        "best_season": "October to March",
        "food_trail": "Kagal Mutton Thali, artisanal jaggery revdi, and freshly crushed cane juice.",
        "villages_towns": [
            {"name": "Murgud", "marathi_name": "मुरगूड", "lat": 16.3980, "lon": 74.2520, "type": "Lake Town & Municipal Council", "est_pop": 14000},
            {"name": "Senapati Kapshi", "marathi_name": "सेनापती कापशी", "lat": 16.4210, "lon": 74.3120, "type": "Historic Maratha Jagir", "est_pop": 9200},
            {"name": "Kagal MIDC", "marathi_name": "कागल एमआयडीसी", "lat": 16.5820, "lon": 74.3210, "type": "Five-Star Industrial Zone", "est_pop": 16500},
            {"name": "Vadanage", "marathi_name": "वडणगे / व्हन्नूर", "lat": 16.5400, "lon": 74.2950, "type": "Agricultural Village", "est_pop": 7800},
        ],
    },
    {
        "id": "radhanagari",
        "name": "Radhanagari",
        "marathi_name": "राधानगरी",
        "headquarters": "Radhanagari",
        "lat": 16.4167,
        "lon": 74.0000,
        "area_sqkm": 724,
        "population_history": [
            {"year": 2015, "value": 208000},
            {"year": 2016, "value": 210000},
            {"year": 2017, "value": 213000},
            {"year": 2018, "value": 215000},
            {"year": 2019, "value": 218000},
            {"year": 2020, "value": 220000},
            {"year": 2021, "value": 223000},
            {"year": 2022, "value": 226000},
            {"year": 2023, "value": 228000},
            {"year": 2024, "value": 231000},
        ],
        "groundwater_mbgl_2024": 4.30,
        "cgwb_status": "Safe",
        "description": "Biodiversity jewel of the Western Ghats UNESCO heritage region. Houses the legendary Radhanagari Dam (Laxmi Talao) and the Dajipur Bison Sanctuary.",
        "top_attractions": [
            {"name": "Radhanagari Wildlife & Bison Sanctuary (Dajipur)", "type": "Wildlife Sanctuary", "desc": "Dense evergreen jungle home to Indian Gaur (Bison), leopards, Malabar giant squirrels, and rare hornbills."},
            {"name": "Radhanagari Dam (Laxmi Talao)", "type": "Historic Dam", "desc": "Engineering triumph commissioned in 1909 by Shahu Maharaj on the Bhogavati River with automatic siphon gates."},
            {"name": "Rautwadi Waterfall", "type": "Waterfall / Eco-tourism", "desc": "Thrilling monsoon waterfall surrounded by untouched forest slopes."},
            {"name": "Dudhganga Kalammawadi Dam", "type": "Dam / Scenic Lake", "desc": "One of the largest earthen dams in Maharashtra with stunning emerald backwaters."},
        ],
        "best_season": "June to September for waterfalls; October to April for wildlife safaris.",
        "food_trail": "Forest wild honey, Gavran chicken curry, and fresh river fish thali.",
        "villages_towns": [
            {"name": "Dajipur", "marathi_name": "दाजीपूर", "lat": 16.3800, "lon": 73.8700, "type": "Bison Wildlife Sanctuary Gateway", "est_pop": 4200},
            {"name": "Fejiwade", "marathi_name": "फेजीवडे", "lat": 16.4100, "lon": 73.9800, "type": "Radhanagari Dam Catchment Hamlet", "est_pop": 3100},
            {"name": "Tarale", "marathi_name": "तारळे", "lat": 16.4700, "lon": 74.0200, "type": "Bhogavati River Agricultural Village", "est_pop": 6800},
            {"name": "Khasbag", "marathi_name": "खासबाग / कसबा तारळे", "lat": 16.4500, "lon": 74.0100, "type": "Forest Foothill Settlement", "est_pop": 5200},
        ],
    },
    {
        "id": "shahuwadi",
        "name": "Shahuwadi",
        "marathi_name": "शाहूवाडी (विशाळगड)",
        "headquarters": "Malkapur",
        "lat": 16.9290,
        "lon": 73.9180,
        "area_sqkm": 1043,
        "population_history": [
            {"year": 2015, "value": 192000},
            {"year": 2016, "value": 194000},
            {"year": 2017, "value": 196000},
            {"year": 2018, "value": 199000},
            {"year": 2019, "value": 201000},
            {"year": 2020, "value": 204000},
            {"year": 2021, "value": 206000},
            {"year": 2022, "value": 209000},
            {"year": 2023, "value": 211000},
            {"year": 2024, "value": 214000},
        ],
        "groundwater_mbgl_2024": 6.10,
        "cgwb_status": "Safe",
        "description": "Rugged mountainous taluka holding eternal Maratha pride. Site of Vishalgad Fort, the heroic battle of Pawankhind, and dense mist-covered Sahyadri passes.",
        "top_attractions": [
            {"name": "Vishalgad Fort", "type": "Historic Fortress", "desc": "Impregnable mountain citadel captured by Shivaji Maharaj in 1659, with deep cliffs on all sides."},
            {"name": "Pawankhind (Ghodkhind)", "type": "Historic Battleground", "desc": "The narrow pass where Baji Prabhu Deshpande made his heroic last stand to enable Shivaji Maharaj's safe escape."},
            {"name": "Amba Ghat", "type": "Mountain Pass", "desc": "Breathtaking mountain pass connecting Kolhapur to Konkan with dramatic cloud formations and paragliding points."},
            {"name": "Manoli Dam & Waterfalls", "type": "Scenic Lake", "desc": "Peaceful lake nestled amidst mountain foliage."},
        ],
        "best_season": "July to January (Monsoon greenery & winter trekking)",
        "food_trail": "Kanda Bhaji, steaming tea at Amba Ghat, and rustic country bhakri.",
        "villages_towns": [
            {"name": "Malkapur", "marathi_name": "मलकापूर", "lat": 16.9280, "lon": 73.9210, "type": "Commercial Ridge Municipal Town", "est_pop": 12800},
            {"name": "Amba", "marathi_name": "आंबा", "lat": 16.9530, "lon": 73.8050, "type": "Sahyadri Eco-Tourism Mountain Hamlet", "est_pop": 3900},
            {"name": "Bambavade", "marathi_name": "बांबवडे", "lat": 16.9020, "lon": 74.0210, "type": "Kadvi Riverbank Agricultural Village", "est_pop": 7400},
            {"name": "Vishalgad Foothills", "marathi_name": "गजापूर / विशाळगड", "lat": 16.8900, "lon": 73.7800, "type": "Fortress Base Historical Village", "est_pop": 2600},
        ],
    },
    {
        "id": "bhudargad",
        "name": "Bhudargad",
        "marathi_name": "भुदरगड (गारगोटी)",
        "headquarters": "Gargoti",
        "lat": 16.3140,
        "lon": 74.1480,
        "area_sqkm": 648,
        "population_history": [
            {"year": 2015, "value": 158000},
            {"year": 2016, "value": 160000},
            {"year": 2017, "value": 162000},
            {"year": 2018, "value": 164000},
            {"year": 2019, "value": 166000},
            {"year": 2020, "value": 168000},
            {"year": 2021, "value": 170000},
            {"year": 2022, "value": 172000},
            {"year": 2023, "value": 174000},
            {"year": 2024, "value": 177000},
        ],
        "groundwater_mbgl_2024": 5.40,
        "cgwb_status": "Safe",
        "description": "A tranquil haven of pristine mountain fortresses, educational foundations (Mouni Vidyapeeth), and dense forested valleys along the Vedganga River.",
        "top_attractions": [
            {"name": "Bhudargad Fort", "type": "Historic Fort", "desc": "Ancient plateau fort dedicated to Goddess Bhairavi with freshwater rock tanks."},
            {"name": "Rangna Fort", "type": "Wilderness Fortress", "desc": "Wild, dense forest fortress on the Goa-Maharashtra frontier surrounded by untouched biodiversity."},
            {"name": "Gargoti Mouni Vidyapeeth", "type": "Educational Heritage", "desc": "Pioneering rural university campus founded in 1952 surrounded by lush botanical gardens."},
            {"name": "Vedganga River Banks", "type": "Riverfront", "desc": "Clear mountain waters supporting traditional organic agriculture."},
        ],
        "best_season": "October to March",
        "food_trail": "Fresh jaggery sugarcane products and traditional village fare.",
        "villages_towns": [
            {"name": "Gargoti", "marathi_name": "गारगोटी", "lat": 16.3120, "lon": 74.1480, "type": "Educational Hub & Mouni Campus", "est_pop": 15800},
            {"name": "Kadgaon", "marathi_name": "कदगाव", "lat": 16.2800, "lon": 74.1200, "type": "Vedganga River Organic Basin", "est_pop": 6100},
            {"name": "Pushpanagar", "marathi_name": "पुष्पनगर", "lat": 16.2400, "lon": 74.1600, "type": "Foothill Agricultural Settlement", "est_pop": 4500},
            {"name": "Shengaon", "marathi_name": "शेनगाव", "lat": 16.3300, "lon": 74.1800, "type": "Farming Cooperative Village", "est_pop": 5300},
        ],
    },
    {
        "id": "ajra",
        "name": "Ajra",
        "marathi_name": "आजरा",
        "headquarters": "Ajra",
        "lat": 16.1170,
        "lon": 74.2080,
        "area_sqkm": 438,
        "population_history": [
            {"year": 2015, "value": 126000},
            {"year": 2016, "value": 127000},
            {"year": 2017, "value": 129000},
            {"year": 2018, "value": 130000},
            {"year": 2019, "value": 132000},
            {"year": 2020, "value": 133000},
            {"year": 2021, "value": 135000},
            {"year": 2022, "value": 137000},
            {"year": 2023, "value": 138000},
            {"year": 2024, "value": 140000},
        ],
        "groundwater_mbgl_2024": 4.90,
        "cgwb_status": "Safe",
        "description": "Celebrated worldwide for GI-tagged aromatic 'Ajra Ghansal' rice and cashew orchards. Home to the mystical Ramteerth waterfall on the Hiranyakeshi River.",
        "top_attractions": [
            {"name": "Ramteerth Waterfall & Caves", "type": "Waterfall / Sacred Site", "desc": "Stunning natural waterfall where Lord Rama is believed to have halted during his exile."},
            {"name": "Ajra Ghansal Paddy Valleys", "type": "Agro-tourism", "desc": "Aromatic, indigenous rice fields filling the valley air with sweet fragrance during harvest season."},
            {"name": "Victoria Jubilee Water Reservoir", "type": "Colonial Heritage Dam", "desc": "19th-century colonial stone masonry dam on the river."},
            {"name": "Uttur Heritage Market", "type": "Cultural Market", "desc": "Traditional weekly trading bazaar of spices, cashews, and mountain produce."},
        ],
        "best_season": "July to February",
        "food_trail": "Aromatic Ajra Ghansal Kheer, steamed Modaks, and roasted Kolhapuri cashews.",
        "villages_towns": [
            {"name": "Ajra Town", "marathi_name": "आजरा शहर", "lat": 16.1150, "lon": 74.2080, "type": "Aromatic Ghansal Rice Trading Center", "est_pop": 19500},
            {"name": "Uttur", "marathi_name": "उत्तूर", "lat": 16.1620, "lon": 74.2580, "type": "Historic Spices & Cashew Market", "est_pop": 11200},
            {"name": "Haldikarwadi", "marathi_name": "हळदीकरवाडी", "lat": 16.0890, "lon": 74.1950, "type": "Chitri Reservoir Catchment Village", "est_pop": 3400},
            {"name": "Gavse", "marathi_name": "गावसे", "lat": 16.1300, "lon": 74.1800, "type": "Highland Agro Village", "est_pop": 4100},
        ],
    },
    {
        "id": "chandgad",
        "name": "Chandgad",
        "marathi_name": "चंदगड",
        "headquarters": "Chandgad",
        "lat": 15.9320,
        "lon": 74.3850,
        "area_sqkm": 947,
        "population_history": [
            {"year": 2015, "value": 196000},
            {"year": 2016, "value": 198000},
            {"year": 2017, "value": 201000},
            {"year": 2018, "value": 203000},
            {"year": 2019, "value": 206000},
            {"year": 2020, "value": 208000},
            {"year": 2021, "value": 211000},
            {"year": 2022, "value": 214000},
            {"year": 2023, "value": 216000},
            {"year": 2024, "value": 219000},
        ],
        "groundwater_mbgl_2024": 4.60,
        "cgwb_status": "Safe",
        "description": "The southern gateway of Kolhapur bordering Goa and Karnataka. Known for massive hydroelectric dams, pristine rainfed forests, and dramatic canyon waterfalls.",
        "top_attractions": [
            {"name": "Tilari Hydroelectric Dam & Canyon Falls", "type": "Hydro Dam & Waterfall", "desc": "Towering waterfalls plunging into emerald canyons on the Maharashtra-Goa border."},
            {"name": "Swapnavel Point", "type": "Scenic Lookout", "desc": "Panoramic high-altitude vantage point providing uninterrupted views of the Konkan plains."},
            {"name": "Gandharvagad Fort", "type": "Hill Fort", "desc": "Historic fort built by Chhatrapati Shivaji Maharaj to overlook the Belgaum passage."},
            {"name": "Jangamhatti Dam", "type": "Lakefront", "desc": "Serene water reservoir surrounded by cashew plantations and evergreen hills."},
        ],
        "best_season": "August to March (Spectacular post-monsoon waterfalls)",
        "food_trail": "Spiced Cashew curry, Kokum sherbet, and traditional multi-grain bhakri.",
        "villages_towns": [
            {"name": "Chandgad Town", "marathi_name": "चंदगड शहर", "lat": 15.9320, "lon": 74.3980, "type": "Southern Plateau Headquarters", "est_pop": 16000},
            {"name": "Shinoli", "marathi_name": "शिनोळी", "lat": 15.9520, "lon": 74.4510, "type": "Industrial & Cashew Processing Hub", "est_pop": 10500},
            {"name": "Kowad", "marathi_name": "कोवाड", "lat": 16.0210, "lon": 74.3820, "type": "Tamraparni River Basin Town", "est_pop": 8200},
            {"name": "Tilari Nagar", "marathi_name": "तिलारी नगर", "lat": 15.8600, "lon": 74.2700, "type": "Hydro Dam & Canyon Frontier Village", "est_pop": 4100},
        ],
    },
    {
        "id": "gadhinglaj",
        "name": "Gadhinglaj",
        "marathi_name": "गडहिंग्लज",
        "headquarters": "Gadhinglaj",
        "lat": 16.2290,
        "lon": 74.3510,
        "area_sqkm": 479,
        "population_history": [
            {"year": 2015, "value": 235000},
            {"year": 2016, "value": 238000},
            {"year": 2017, "value": 241000},
            {"year": 2018, "value": 245000},
            {"year": 2019, "value": 248000},
            {"year": 2020, "value": 252000},
            {"year": 2021, "value": 256000},
            {"year": 2022, "value": 260000},
            {"year": 2023, "value": 264000},
            {"year": 2024, "value": 268000},
        ],
        "groundwater_mbgl_2024": 8.80,
        "cgwb_status": "Safe",
        "description": "Vibrant commercial and educational hub along the Ghataprabha River. Famous for the Samangad fort where Maratha forces defeated British garrisons in 1844.",
        "top_attractions": [
            {"name": "Samangad Fort", "type": "Hill Fort / Heritage", "desc": "Fortified plateau where the Gadkari rebellion of 1844 took place against the British East India Company."},
            {"name": "Ghataprabha River Promenade", "type": "River Valley", "desc": "Lush green riverside providing fresh water to extensive chili and vegetable farms."},
            {"name": "Kalbhairav Temple", "type": "Ancient Shrine", "desc": "Centuries-old stone temple drawing devotees across southern Maharashtra."},
        ],
        "best_season": "October to March",
        "food_trail": "Gadhinglaj Red Chili spice blends, authentic jaggery sweets, and savory snacks.",
        "villages_towns": [
            {"name": "Gadhinglaj City", "marathi_name": "गडहिंग्लज शहर", "lat": 16.2290, "lon": 74.3510, "type": "Ghataprabha Agro-Commercial City", "est_pop": 34000},
            {"name": "Nesari", "marathi_name": "नेसरी", "lat": 16.1420, "lon": 74.3310, "type": "Historic Battleground of Prataprao Gujar", "est_pop": 8900},
            {"name": "Kadgaon", "marathi_name": "कदगाव (गडहिंग्लज)", "lat": 16.2100, "lon": 74.3800, "type": "Red Chili & Jaggery Village", "est_pop": 6400},
            {"name": "Bhadgaon", "marathi_name": "भडगाव", "lat": 16.2450, "lon": 74.3200, "type": "River Valley Agricultural Village", "est_pop": 5700},
        ],
    },
    {
        "id": "gaganbawda",
        "name": "Gaganbawda",
        "marathi_name": "गगनबावडा",
        "headquarters": "Bawda",
        "lat": 16.5440,
        "lon": 73.8290,
        "area_sqkm": 293,
        "population_history": [
            {"year": 2015, "value": 37000},
            {"year": 2016, "value": 37500},
            {"year": 2017, "value": 38000},
            {"year": 2018, "value": 38600},
            {"year": 2019, "value": 39100},
            {"year": 2020, "value": 39700},
            {"year": 2021, "value": 40300},
            {"year": 2022, "value": 40900},
            {"year": 2023, "value": 41500},
            {"year": 2024, "value": 42100},
        ],
        "groundwater_mbgl_2024": 3.00,
        "cgwb_status": "Safe",
        "description": "The highest-rainfall plateau in Kolhapur, known as the 'Cherrapunji of southern Maharashtra' with over 5,000 mm of annual monsoon rain. Home to the cloudswept Gagangarh Fort and Gagangiri Maharaj Ashram.",
        "top_attractions": [
            {"name": "Gagangarh Fort & Ashram", "type": "Hill Fort / Spiritual", "desc": "Clifftop fortress and meditation cave ashram of Swami Gagangiri Maharaj shrouded in clouds."},
            {"name": "Bawda Ghat", "type": "Scenic Mountain Pass", "desc": "Spectacular serpentine pass dropping sharply towards Konkan, often featured in Indian cinema."},
            {"name": "Karul Ghat & Bhuibawda Ghat", "type": "Twin Ghat Passes", "desc": "Twin scenic passes cutting through ancient Sahyadri basalt cliffs with panoramic vistas."},
            {"name": "Lakhmapur Dam", "type": "High Altitude Lake", "desc": "Pristine mountain reservoir reflecting monsoon clouds and surrounding jungle peaks."},
        ],
        "best_season": "June to September for high-monsoon fog and waterfalls; October to February for clear cliff views.",
        "food_trail": "Kanda Bhaji with green thecha, steaming chai at mist viewpoints, and hot pithla bhakri.",
        "villages_towns": [
            {"name": "Bawda Town", "marathi_name": "बावडा", "lat": 16.5440, "lon": 73.8290, "type": "Highest-Rainfall Clifftop Town", "est_pop": 5100},
            {"name": "Asalaj", "marathi_name": "अंसलज", "lat": 16.5620, "lon": 73.8120, "type": "Valley Rainforest Hamlet", "est_pop": 2100},
            {"name": "Khadbale", "marathi_name": "खडबळे", "lat": 16.5210, "lon": 73.8450, "type": "Ghat Mist & Tea Farm Village", "est_pop": 1800},
            {"name": "Dhengwali", "marathi_name": "धेंगवळी", "lat": 16.5100, "lon": 73.8100, "type": "Deep Sahyadri Catchment Hamlet", "est_pop": 1400},
        ],
    },
]
