import React from 'react';
import { useApp } from '../../context/AppContext';
import { FEATURED_ECHOES } from '../../data/locations';
import { Star, Play, BookOpen, ChevronRight, Sparkles } from 'lucide-react';

const MODE_BADGE_STYLES = {
  historical: "bg-amber-600 text-white",
  legend: "bg-purple-600 text-white",
  guide: "bg-sky-600 text-white",
  story: "bg-rose-600 text-white",
  culture: "bg-emerald-600 text-white"
};

const MODE_DIFF_STYLES = {
  historical: "bg-amber-50/90 text-amber-950 border border-amber-200/60",
  legend: "bg-purple-50/90 text-purple-950 border border-purple-200/60",
  guide: "bg-sky-50/90 text-sky-950 border border-sky-200/60",
  story: "bg-rose-50/90 text-rose-950 border border-rose-200/60",
  culture: "bg-emerald-50/90 text-emerald-950 border border-emerald-200/60"
};

export const FeaturedEchoesSection = () => {
  const { openStoryModal, playNarration, setCurrentPage, selectLocation, allLocations } = useApp();

  const handleListen = (echo) => {
    // Find matching location details for full text
    const loc = allLocations.find(l => l.id === echo.id);
    const fullText = loc?.experiences[echo.mode]?.fullText || echo.description;
    playNarration(echo.title, echo.location, fullText, 210, echo.mode === 'legend' ? 'futuristic' : 'temple_bells');
  };

  const handleReadStory = (echo) => {
    const loc = allLocations.find(l => l.id === echo.id);
    const exp = loc?.experiences[echo.mode];
    openStoryModal({
      ...echo,
      fullText: exp?.fullText || echo.description,
      subtitle: exp?.subtitle,
      whyDifferent: exp?.whyDifferent || echo.whyDifferent,
      tags: exp?.tags || echo.tags
    });
  };

  return (
    <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 md:py-24">
      
      {/* Header & See All Button */}
      <div className="mb-10 flex flex-wrap items-end justify-between gap-4">
        <div>
          <h2 className="text-3xl font-bold sm:text-4xl text-foreground font-serif">
            Featured Echoes
          </h2>
          <p className="mt-2 max-w-2xl text-sm sm:text-base text-muted-foreground leading-relaxed">
            Sample stories generated by GeoEchoAI from amazing places around the world. Each card demonstrates a different experience mode, so the contrast is easy to feel.
          </p>
        </div>

        <button 
          onClick={() => setCurrentPage('explore')}
          className="inline-flex items-center justify-center gap-1 rounded-full border border-border bg-card px-4 py-2 text-xs sm:text-sm font-semibold text-foreground shadow-soft transition-all hover:bg-stone-50 hover:border-primary/40 active:scale-95"
        >
          <span>See all Echoes</span>
          <ChevronRight className="h-4 w-4" />
        </button>
      </div>

      {/* 4/5 Column Grid of Cards */}
      <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-5">
        {FEATURED_ECHOES.map((echo) => {
          const badgeClass = MODE_BADGE_STYLES[echo.mode] || "bg-primary text-white";
          const diffClass = MODE_DIFF_STYLES[echo.mode] || "bg-stone-50 text-foreground";

          return (
            <article 
              key={echo.id}
              className="group overflow-hidden rounded-3xl border border-border bg-card shadow-soft transition-all duration-300 hover:shadow-card hover:-translate-y-1 flex flex-col justify-between"
            >
              {/* Card Image with Floating Mode Badge */}
              <div className="relative overflow-hidden aspect-[5/4] bg-stone-100">
                <img 
                  src={echo.image} 
                  alt={echo.title}
                  loading="lazy"
                  className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-105"
                />
                <span className={`absolute left-3 bottom-3 rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-wider shadow-sm ${badgeClass}`}>
                  {echo.modeLabel}
                </span>
              </div>

              {/* Card Body */}
              <div className="p-4 sm:p-5 flex-1 flex flex-col justify-between">
                <div>
                  
                  {/* Title & Star Rating */}
                  <div className="flex items-center justify-between gap-2">
                    <h3 
                      onClick={() => handleReadStory(echo)}
                      className="text-base font-bold text-foreground cursor-pointer hover:text-primary transition-colors line-clamp-1"
                    >
                      {echo.title}
                    </h3>
                    <span className="flex shrink-0 items-center gap-1 text-xs font-semibold text-primary">
                      <Star className="h-3.5 w-3.5 fill-primary text-primary" />
                      {echo.rating}
                    </span>
                  </div>

                  {/* Location Subtitle */}
                  <p className="mt-1 text-xs font-medium text-muted-foreground">
                    {echo.location}
                  </p>

                  {/* 2-line Evocative Summary */}
                  <p className="mt-2 text-xs sm:text-sm text-muted-foreground line-clamp-3 leading-relaxed">
                    {echo.description}
                  </p>

                  {/* Theme Tags */}
                  <div className="mt-3 flex flex-wrap gap-1.5">
                    {echo.tags.map((tag, idx) => (
                      <span 
                        key={idx}
                        className="rounded-full bg-stone-100 px-2 py-0.5 text-[10px] font-semibold text-stone-700"
                      >
                        {tag}
                      </span>
                    ))}
                  </div>

                  {/* "Why This Feels Different" Callout Box */}
                  <div className={`mt-3.5 rounded-2xl p-3 ${diffClass}`}>
                    <div className="text-[10px] font-black uppercase tracking-[0.18em] opacity-80 mb-1">
                      Why this feels different
                    </div>
                    <p className="text-xs leading-relaxed opacity-95">
                      {echo.whyDifferent}
                    </p>
                  </div>

                </div>

                {/* Bottom Action Buttons: Listen & Read Story */}
                <div className="mt-4 flex gap-2 pt-2 border-t border-border/50">
                  <button
                    onClick={() => handleListen(echo)}
                    className="flex flex-1 items-center justify-center gap-1.5 rounded-xl bg-primary-soft py-2 px-2 text-xs font-bold text-primary hover:bg-primary/20 transition-colors active:scale-95"
                  >
                    <Play className="h-3.5 w-3.5 fill-primary text-primary" />
                    <span>Listen</span>
                  </button>

                  <button
                    onClick={() => handleReadStory(echo)}
                    className="flex flex-1 items-center justify-center gap-1.5 rounded-xl border border-border py-2 px-2 text-xs font-bold text-foreground hover:bg-stone-50 transition-colors active:scale-95"
                  >
                    <BookOpen className="h-3.5 w-3.5" />
                    <span>Read Story</span>
                  </button>
                </div>

              </div>

            </article>
          );
        })}
      </div>

    </section>
  );
};
